import { typesImages } from './images';

const {
  bug,
  dark,
  dragon,
  eletric,
  fairy,
  fighter,
  fire,
  flying,
  ghost,
  grass,
  ground,
  ice,
  steel,
  normal,
  poison,
  psychic,
  rock,
  water,
} = typesImages || {};

const types = [
  {
    image: bug,
    name: 'Bug',
    color: '#91c12f',
    strengths: [dark, grass, psychic],
    weaknesses: [fire, flying, rock],
    immunities: [],
  },
  {
    image: dark,
    name: 'Dark',
    color: '#5B5464',
    strengths: [ghost, psychic],
    weaknesses: [bug, fairy, fighter],
    immunities: [psychic],
  },
  {
    image: dragon,
    name: 'Dragon',
    color: '#0B6DC4',
    strengths: [dragon],
    weaknesses: [dragon, fairy, ice],
    immunities: [],
  },
  {
    image: eletric,
    name: 'Eletric',
    color: '#F4D23B',
    strengths: [water, flying],
    weaknesses: [ground],
    immunities: [],
  },
  {
    image: fairy,
    name: 'Fairy',
    color: '#ED8FE7',
    strengths: [dark, dragon, psychic],
    weaknesses: [steel, poison],
    immunities: [dragon],
  },
  {
    image: fighter,
    name: 'Fighter',
    color: '#CE416B',
    strengths: [dark, ice, normal, rock, steel],
    weaknesses: [fairy, flying, psychic],
    immunities: [],
  },
  {
    image: fire,
    name: 'Fire',
    color: '#FE9C58',
    strengths: [bug, grass, ice, steel],
    weaknesses: [rock, ground, water],
    immunities: [],
  },
  {
    image: flying,
    name: 'Flying',
    color: '#8AAAE3',
    strengths: [bug, fighter, grass],
    weaknesses: [eletric, ice, rock],
    immunities: [ground],
  },
  {
    image: ghost,
    name: 'Ghost',
    color: '#5269AD',
    strengths: [ghost, psychic],
    weaknesses: [dark, ghost],
    immunities: [normal, fighter],
  },
  {
    image: grass,
    name: 'Grass',
    color: '#62BC5A',
    strengths: [ground, rock, water],
    weaknesses: [bug, fire, flying, ice, poison],
    immunities: [],
  },
  {
    image: ground,
    name: 'Ground',
    color: '#D97845',
    strengths: [eletric, fire, poison, rock, steel],
    weaknesses: [ice, grass, water],
    immunities: [],
  },
  {
    image: ice,
    name: 'Ice',
    color: '#73CEBF',
    strengths: [dragon, flying, grass, ground],
    weaknesses: [fighter, fire, rock, steel],
    immunities: [],
  },
  {
    image: steel,
    name: 'Steel',
    color: '#5A8EA1',
    strengths: [fairy, ice, rock],
    weaknesses: [fighter, fire, ground],
    immunities: [poison],
  },
  {
    image: normal,
    name: 'Normal',
    color: '#919AA3',
    strengths: [],
    weaknesses: [fighter],
    immunities: [],
  },
  {
    image: poison,
    name: 'Poison',
    color: '#B567CD',
    strengths: [fairy, grass],
    weaknesses: [ground, psychic],
    immunities: [],
  },
  {
    image: psychic,
    name: 'Psychic',
    color: '#FD7078',
    strengths: [fighter, poison],
    weaknesses: [bug, dark, ghost],
    immunities: [],
  },
  {
    image: rock,
    name: 'Rock',
    color: '#C4B78B',
    strengths: [bug, fire, flying, ice],
    weaknesses: [fighter, grass, ground, steel, water],
    immunities: [],
  },
  {
    image: water,
    name: 'Water',
    color: '#5090D7',
    strengths: [fire, ground, rock],
    weaknesses: [eletric, grass],
    immunities: [],
  },
];

export { types };
